### ISSUE TITLE
Add git ignore to stop tracking bin, obj and .vs folders

### ISSUE THREAD

**Issue by yeseniamolinab** [lmolinabe/PersonalWork#1]
this can help you ;)

https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by lmolinabe** [comment]
After some testing, the local .gitignore file is working.
The unnecesary folders and files were ignored in the last commit/push.
Thanks Yesy!!

**Comment by yeseniamolinab** [comment]
LGTM 👍 😄
